board_info:
  name: fullcurrent
  description: fullCURRENT Motor Controller
  base_id: 0x400

listen:
  - name: fullcurrent_analog1
  - name: fullcurrent_analog2

packets:
  - name: analog1
    description: Analog Voltages
    offset: 0
    endian: little
    data:
      - name: ia
        type: float
        description: Phase A Current
      - name: ib
        type: float
        description: Phase B Current

  - name: analog2
    description: Analog Voltages
    offset: 1
    endian: little
    data:
      - name: ic
        type: float
        description: Phase C Current
      - name: va
        type: float
        description: Phase A Voltage

  - name: analog3
    description: Analog Voltages
    offset: 2
    endian: little
    data:
      - name: vb
        type: float
        description: Phase B Voltage
      - name: vc
        type: float
        description: Phase C Voltage
